# Generated by Django 5.0.1 on 2024-01-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowersCount',
            new_name='TrackersCount',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='Pet',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='id_user',
            new_name='id_pet',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='pet',
        ),
        migrations.RenameField(
            model_name='trackerscount',
            old_name='follower',
            new_name='Pet',
        ),
        migrations.RenameField(
            model_name='trackerscount',
            old_name='user',
            new_name='tracker',
        ),
    ]
