# Generated by Django 5.0.1 on 2024-01-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_followerscount_trackerscount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackersCount',
            new_name='FollowersCount',
        ),
        migrations.RenameField(
            model_name='followerscount',
            old_name='Pet',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='followerscount',
            old_name='tracker',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Pet',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='id_pet',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='pet',
            new_name='user',
        ),
    ]
